"""init

Revision ID: f51287fd558b
Revises: 
Create Date: 2025-04-01 01:00:20.426005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51287fd558b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripparticipant')
    op.drop_table('trip')
    op.drop_table('interest')
    op.drop_table('userinterest')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender'), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('travel_style', postgresql.ENUM('adventure', 'comfort', 'cultural', 'party', 'nature', name='travelstyle'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('userinterest',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], name='userinterest_interest_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userinterest_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id', name='userinterest_pkey')
    )
    op.create_table('interest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='interest_pkey')
    )
    op.create_table('trip',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trip_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departure_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='trip_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trip_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tripparticipant',
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='participationstatus'), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name='tripparticipant_trip_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tripparticipant_user_id_fkey'),
    sa.PrimaryKeyConstraint('trip_id', 'user_id', name='tripparticipant_pkey')
    )
    # ### end Alembic commands ###
